incremental_ingest:
	python3 source/incremental_copy_from_csv.py  ingest_rdbms_requests_table.yaml

full_ingest:
	python3 source/full_copy_from_csv.py  ingest_rdbms_requests_table.yaml

data_analysis_report:
	python3 source/data_analysis_report.py
