initialize:
	# --< Landing Zone >-----------------------------------
	rm -rf landing
	mkdir landing
	mkdir landing/pqrs
	
	# --< Raw Zone >---------------------------------------
	rm -rf raw
	mkdir raw
	mkdir raw/pqrs
	
	# --< Cleansed Zone >----------------------------------
	rm -rf cleansed
	mkdir cleansed
	mkdir cleansed/pqrs

	
	