initialize:
	# --< Landing Zone >-----------------------------------
	rm -rf landing
	mkdir landing
	mkdir landing/pqrs
	
	# --< Raw Zone >---------------------------------------
	rm -rf raw
	mkdir raw
	mkdir raw/pqrs
	
	# --< Cleansed Zone >----------------------------------
	rm -rf cleansed
	mkdir cleansed


	# --< Business Zone >----------------------------------
	rm -rf business
	mkdir business
	mkdir business/reports
	